name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.SK_PROJECT_SECRET }}
          repository: Yansier/sk-project
          ssh-key: ${{ secrets.SK_PROJECT_SECRET_2 }}
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build


      - name: Deploy to GitHub Pages   
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
      - name: Deploy to GitHub Pages
        run: |
            # 假设构建产物在 dist 目录
            cd dist
            git init
            git checkout -b gh-pages
            git add .
            git commit -m "Deploy"
            git push -f https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git gh-pages
   
 
    permissions: # 关键！授予写入权限
      contents: write
      pages: write
      id-token: write

      
