name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      # 1. 检出代码（简化版）
      - uses: actions/checkout@v3

      # 2. 安装 Node.js
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. 安装依赖
      - name: Install dependencies
        run: npm ci  # 更干净的安装方式

      # 4. 构建项目（单次）
      - name: Build
        run: npm run build || exit 1

      # 5. 部署（只保留一种方式）
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # 可选：强制清空历史
          force_orphan: true